<div align="center">
    <h1>Exploratory Data Analysis of Shark Attack Data</h1>
</div>

## Imports

In [1]:
import pandas as pd

%run "../server/utils/print_utilities.py"
%run "../server/utils/preprocessing/type_cleaner.py"
%run "../server/utils/preprocessing/country_cleaner.py"
%run "../server/utils/preprocessing/activity_cleaner.py"
%run "../server/utils/preprocessing/gender_cleaner.py"
%run "../server/utils/preprocessing/age_cleaner.py"
%run "../server/utils/preprocessing/fatality_cleaner.py"
%run "../server/utils/preprocessing/time_cleaner.py"
%run "../server/utils/preprocessing/species_cleaner.py"

## Dataset Contents

In [2]:
DATA_PATH = "../server/data/attacks.csv"

data_frame = pd.read_csv(
    DATA_PATH,
    encoding="latin1",
    usecols=[
        "Date", "Type", "Country", "Area", "Location", "Activity", "Sex ", "Age", "Fatal (Y/N)", "Time", "Species "
    ]
)

data_frame = data_frame.rename(
    columns={
        "Sex ": "Gender",
        "Fatal (Y/N)": "Fatal",
        "Species ": "Species"
    }
)

print(data_frame.fillna("Unknown").head(10))

          Date        Type    Country             Area  \
0  25-Jun-2018     Boating        USA       California
1  18-Jun-2018  Unprovoked        USA          Georgia
2  09-Jun-2018     Invalid        USA           Hawaii
3  08-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
4  04-Jun-2018    Provoked     MEXICO           Colima
5  03-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
6  03-Jun-2018  Unprovoked     BRAZIL       Pernambuco
7  27-May-2018  Unprovoked        USA          Florida
8  26-May-2018  Unprovoked        USA          Florida
9  26-May-2018  Unprovoked        USA          Florida

                                            Location      Activity Gender  \
0                        Oceanside, San Diego County      Paddling      F
1                     St. Simon Island, Glynn County      Standing      F
2                                       Habush, Oahu       Surfing      M
3                                 Arrawarra Headland       Surfing      M
4                                           La Ticla   Free diving      M
5                                 Flat Rock, Ballina  Kite surfing      M
6                              Piedade Beach, Recife      Swimming      M
7  Lighhouse Point Park, Ponce Inlet, Volusia County       Fishing      M
8                       Cocoa Beach, Brevard  County       Walking      M
9                      Daytona Beach, Volusia County      Standing      M

       Age Fatal            Time          Species
0       57     N           18h00      White shark
1       11     N   14h00  -15h00          Unknown
2       48     N           07h45          Unknown
3  Unknown     N         Unknown        2 m shark
4  Unknown     N         Unknown  Tiger shark, 3m
5  Unknown     N         Unknown          Unknown
6       18     Y  Late afternoon      Tiger shark
7       52     N         Unknown  Lemon shark, 3'
8       15     N           17h00   Bull shark, 6'
9       12     N           14h00          Unknown

## Feature Engineering

### Before Preprocessing

In [3]:
data_frame.describe(include="all").T

         count unique                               top  freq
Date      6302   5433                              1957    11
Type      6298      8                        Unprovoked  4595
Country   6252    212                               USA  2229
Area      5847    825                           Florida  1037
Location  5762   4108  New Smyrna Beach, Volusia County   163
Activity  5758   1532                           Surfing   971
Gender    5737      6                                 M  5094
Age       3471    157                                17   154
Fatal     5763      8                                 N  4293
Time      2948    366                         Afternoon   187
Species   3464   1549                       White shark   163

### Cleaning Date Column

In [4]:
print_num_empty_recs(data_frame, "Date")

Encountered 1 null value(s).

In [5]:
data_frame["Date"].value_counts()

Date
1957                                                                11
1942                                                                 9
1956                                                                 8
1958                                                                 7
1950                                                                 7
                                                                    ..
No date (3 days after preceding incident) & prior to 19-Jul-1913     1
Before 19-Jul-1913                                                   1
1900-1905                                                            1
1883-1889                                                            1
1845-1853                                                            1
Name: count, Length: 5433, dtype: int64

### Cleaning Type Column

In [6]:
data_frame["Type"] = data_frame["Type"].apply(categorize_type)
print_num_empty_recs(data_frame, "Type")
print_num_expected_strings(
    data_frame,
    "Type",
    value_to_count="Questionable"
)

Encountered 5 null value(s).
Encountered 2 unexpected input value(s).

In [7]:
data_frame["Type"] = data_frame["Type"].replace("Questionable", None)
data_frame["Type"].value_counts()

Type
Unprovoked      4595
Provoked         574
Invalid          547
Boating          341
Sea Disaster     239
Name: count, dtype: int64

### Cleaning Country Column

In [8]:
data_frame["Country"] = data_frame["Country"].apply(categorize_country)
print_num_empty_recs(data_frame, "Country")
print_num_expected_strings(
    data_frame,
    "Country",
    value_to_count="Unknown"
)

Encountered 51 null value(s).
Encountered 150 unexpected input value(s).

In [9]:
data_frame["Country"] = data_frame["Country"].replace("Unknown", None)
data_frame["Country"].value_counts()

Country
USA                 2229
AUSTRALIA           1338
SOUTH AFRICA         579
PAPUA NEW GUINEA     134
NEW ZEALAND          128
                    ...
GREENLAND              1
SWEDEN                 1
HND                    1
DJIBOUTI               1
BHR                    1
Name: count, Length: 145, dtype: int64

### Cleaning Area Column

In [10]:
data_frame["Area"].value_counts()

Area
Florida                              1037
New South Wales                       486
Queensland                            311
Hawaii                                298
California                            290
                                     ...
Riau Province                           1
Bikini Atoll                            1
Between New Ireland & New Britain       1
Ba Ria-Vung Tau  Province               1
Moala Island                            1
Name: count, Length: 825, dtype: int64

### Cleaning Location Columns

In [11]:
data_frame["Location"].value_counts()

Location
New Smyrna Beach, Volusia County       163
Daytona Beach, Volusia County           30
Ponce Inlet, Volusia County             20
Melbourne Beach, Brevard County         18
Myrtle Beach, Horry County              17
                                      ...
                                         1
Roebuck Bay                              1
Ocracoke Inlet                           1
Panama Bay 8ºN, 79ºW                     1
Below the English fort, Trincomalee      1
Name: count, Length: 4108, dtype: int64

### Cleaning Activity Column

In [12]:
data_frame["Activity"] = data_frame["Activity"].apply(categorize_activity)
print_num_empty_recs(data_frame, "Activity")
print_num_expected_strings(
    data_frame,
    "Activity",
    value_to_count="Other"
)

Encountered 545 null value(s).
Encountered 482 unexpected input value(s).

In [13]:
data_frame["Activity"].value_counts()

Activity
Surfing                    1384
Swimming                   1226
Fishing                    1160
Diving                      505
Other                       482
Boating                     363
Wading in Shallow Water     302
Floating/Treading Water     125
Interacting with Sharks     118
Snorkeling                   93
Name: count, dtype: int64

### Cleaning Gender Column

In [14]:
data_frame["Gender"] = data_frame["Gender"].apply(categorize_gender)
print_num_empty_recs(data_frame, "Gender")
print_num_expected_strings(
    data_frame,
    "Gender",
    value_to_count="Unknown"
)

Encountered 566 null value(s).
Encountered 2 unexpected input value(s).

In [15]:
data_frame["Gender"] = data_frame["Gender"].replace("Unknown", None)
data_frame["Gender"].value_counts()

Gender
M    5098
F     637
Name: count, dtype: int64

### Cleaning Age Column

In [16]:
data_frame["Age"] = data_frame["Age"].apply(categorize_age)
print_num_empty_recs(data_frame, "Age")
print_num_expected_strings(
    data_frame,
    "Age",
    value_to_count="Unknown"
)

Encountered 2832 null value(s).
Encountered 15 unexpected input value(s).

In [17]:
data_frame["Age"] = data_frame["Age"].replace("Unknown", None)
data_frame["Age"].value_counts()

Age
17    155
16    154
18    150
19    145
20    145
     ...
84      1
87      1
67      1
81      1
2       1
Name: count, Length: 81, dtype: int64

### Cleaning Fatality Column

In [18]:
data_frame["Fatal"] = data_frame["Fatal"].apply(categorize_fatality)
print_num_empty_recs(data_frame, "Fatal")
print_num_expected_strings(
    data_frame,
    "Fatal",
    value_to_count="Unknown"
)

Encountered 540 null value(s).
Encountered 72 unexpected input value(s).

In [19]:
data_frame["Fatal"] = data_frame["Fatal"].replace("Unknown", None)
data_frame["Fatal"].value_counts()

Fatal
N    4302
Y    1389
Name: count, dtype: int64

### Cleaning Time Column

In [20]:
data_frame["Time"] = data_frame["Time"].apply(categorize_time)
print_num_empty_recs(data_frame, "Time")
print_num_expected_strings(
    data_frame,
    "Time",
    value_to_count="Unknown"
)

Encountered 3366 null value(s).
Encountered 2 unexpected input value(s).

In [21]:
data_frame["Time"] = data_frame["Time"].replace("Unknown", None)
data_frame["Time"].value_counts()

Time
Afternoon    1387
Morning       949
Evening       477
Night         122
Name: count, dtype: int64

### Cleaning Species Column

In [22]:
data_frame["Species"] = data_frame["Species"].apply(categorize_species)
print_num_empty_recs(data_frame, "Species")
print_num_expected_strings(
    data_frame,
    "Species",
    value_to_count="Unknown"
)

Encountered 2839 null value(s).
Encountered 1551 unexpected input value(s).

In [23]:
data_frame["Species"] = data_frame["Species"].replace("Unknown", None)
data_frame["Species"].value_counts()

Species
Great White Shark         635
Tiger Shark               285
Bull Shark                208
Sand Tiger Shark           83
Copper Shark               77
Blacktip Shark             76
Shortfin Mako Shark        61
Nurse Shark                57
Wobbegong Shark            50
Hammerhead Shark           48
Spinner Shark              45
Blue Shark                 40
Lemon Shark                35
Oceanic Whitetip Shark     24
Grey Reef Shark            19
Sevengill shark            19
Sand Shark                 19
Unspecified Reef Shark     17
Caribbean Reef Shark       16
Dusky Shark                12
Spiny Dogfish              10
Sandbar Shark               8
Carpet Shark                8
Galapagos Shark             7
Porbeagle Shark             7
Basking Shark               7
Angel Shark                 6
Silky Shark                 4
Whitetip Reef Shark         4
Thresher Shark              4
Salmon Shark                3
Whale Shark                 3
Catshark                    3
Goblin Shark                2
Blackfin Shark              2
Leopard Shark               2
Silvertip Shark             2
Cookiecutter Shark          1
Port Jackson Shark          1
Longfin Mako Shark          1
Soupfin Shark               1
Sixgill shark               1
Name: count, dtype: int64

## Summary

### After Preprocessing

In [24]:
print(data_frame.fillna("Unknown").head(10))

          Date        Type    Country             Area  \
0  25-Jun-2018     Boating        USA       California
1  18-Jun-2018  Unprovoked        USA          Georgia
2  09-Jun-2018     Invalid        USA           Hawaii
3  08-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
4  04-Jun-2018    Provoked        MEX           Colima
5  03-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
6  03-Jun-2018  Unprovoked     BRAZIL       Pernambuco
7  27-May-2018  Unprovoked        USA          Florida
8  26-May-2018  Unprovoked        USA          Florida
9  26-May-2018  Unprovoked        USA          Florida

                                            Location                 Activity  \
0                        Oceanside, San Diego County                  Surfing
1                     St. Simon Island, Glynn County  Wading in Shallow Water
2                                       Habush, Oahu                  Surfing
3                                 Arrawarra Headland                  Surfing
4                                           La Ticla                   Diving
5                                 Flat Rock, Ballina                  Surfing
6                              Piedade Beach, Recife                 Swimming
7  Lighhouse Point Park, Ponce Inlet, Volusia County                  Fishing
8                       Cocoa Beach, Brevard  County  Wading in Shallow Water
9                      Daytona Beach, Volusia County  Wading in Shallow Water

  Gender      Age Fatal       Time            Species
0      F       57     N    Evening  Great White Shark
1      F       11     N  Afternoon            Unknown
2      M       48     N    Morning            Unknown
3      M  Unknown     N    Unknown            Unknown
4      M  Unknown     N    Unknown        Tiger Shark
5      M  Unknown     N    Unknown            Unknown
6      M       18     Y  Afternoon        Tiger Shark
7      M       52     N    Unknown        Lemon Shark
8      M       15     N    Evening         Bull Shark
9      M       12     N  Afternoon            Unknown

In [25]:
data_frame.describe(include="all").T

         count unique                               top  freq
Date      6302   5433                              1957    11
Type      6296      5                        Unprovoked  4595
Country   6102    145                               USA  2229
Area      5847    825                           Florida  1037
Location  5762   4108  New Smyrna Beach, Volusia County   163
Activity  5758     10                           Surfing  1384
Gender    5735      2                                 M  5098
Age       3456     81                                17   155
Fatal     5691      2                                 N  4302
Time      2935      4                         Afternoon  1387
Species   1913     42                 Great White Shark   635