<div align="center">
    <h1>Exploratory Data Analysis of Shark Attack Data</h1>
</div>

## Imports

In [227]:
import pandas as pd

%run "../utils/preprocessing/gender_cleaner.py"
%run "../utils/preprocessing/fatality_cleaner.py"
%run "../utils/preprocessing/time_cleaner.py"

## Dataset Contents

In [228]:
DATA = "../data/attacks.csv"

data_frame = pd.read_csv(
    DATA,
    encoding="latin1",
    usecols=[
        "Date", "Type", "Country", "Area", "Location", "Activity", "Sex ", "Age", "Fatal (Y/N)", "Time", "Species "
    ]
)

data_frame = data_frame.rename(
    columns={
        "Sex ": "Gender",
        "Fatal (Y/N)": "Fatal",
        "Species ": "Species"
    }
)

print(data_frame.fillna("Unknown").head(10))

          Date        Type    Country             Area  \
0  25-Jun-2018     Boating        USA       California
1  18-Jun-2018  Unprovoked        USA          Georgia
2  09-Jun-2018     Invalid        USA           Hawaii
3  08-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
4  04-Jun-2018    Provoked     MEXICO           Colima
5  03-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
6  03-Jun-2018  Unprovoked     BRAZIL       Pernambuco
7  27-May-2018  Unprovoked        USA          Florida
8  26-May-2018  Unprovoked        USA          Florida
9  26-May-2018  Unprovoked        USA          Florida

                                            Location      Activity Gender  \
0                        Oceanside, San Diego County      Paddling      F
1                     St. Simon Island, Glynn County      Standing      F
2                                       Habush, Oahu       Surfing      M
3                                 Arrawarra Headland       Surfing      M
4                                           La Ticla   Free diving      M
5                                 Flat Rock, Ballina  Kite surfing      M
6                              Piedade Beach, Recife      Swimming      M
7  Lighhouse Point Park, Ponce Inlet, Volusia County       Fishing      M
8                       Cocoa Beach, Brevard  County       Walking      M
9                      Daytona Beach, Volusia County      Standing      M

       Age Fatal            Time          Species
0       57     N           18h00      White shark
1       11     N   14h00  -15h00          Unknown
2       48     N           07h45          Unknown
3  Unknown     N         Unknown        2 m shark
4  Unknown     N         Unknown  Tiger shark, 3m
5  Unknown     N         Unknown          Unknown
6       18     Y  Late afternoon      Tiger shark
7       52     N         Unknown  Lemon shark, 3'
8       15     N           17h00   Bull shark, 6'
9       12     N           14h00          Unknown

## Feature Engineering

### Before Preprocessing

In [229]:
data_frame.describe(include="all").T

         count unique                               top  freq
Date      6302   5433                              1957    11
Type      6298      8                        Unprovoked  4595
Country   6252    212                               USA  2229
Area      5847    825                           Florida  1037
Location  5762   4108  New Smyrna Beach, Volusia County   163
Activity  5758   1532                           Surfing   971
Gender    5737      6                                 M  5094
Age       3471    157                                17   154
Fatal     5763      8                                 N  4293
Time      2948    366                         Afternoon   187
Species   3464   1549                       White shark   163

## Cleaning Gender Column

In [230]:
data_frame["Gender"] = data_frame["Gender"].apply(categorize_gender)

Encountered unexpected string: "LLI"
Encountered unexpected string: "."

## Cleaning Fatality Column

In [231]:
data_frame["Fatal"] = data_frame["Fatal"].apply(categorize_fatality)

Encountered unexpected string: "2017"

### Cleaning Time Column

In [232]:
data_frame["Time"] = data_frame["Time"].apply(categorize_time)

Encountered improper time string: "2 hours after Opperman".
Encountered improper time string: "FATAL  (Wire netting installed at local beaches after this incident.)".

## Summary

### After Preprocessing

In [233]:
print(data_frame.fillna("Unknown").head(10))

          Date        Type    Country             Area  \
0  25-Jun-2018     Boating        USA       California
1  18-Jun-2018  Unprovoked        USA          Georgia
2  09-Jun-2018     Invalid        USA           Hawaii
3  08-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
4  04-Jun-2018    Provoked     MEXICO           Colima
5  03-Jun-2018  Unprovoked  AUSTRALIA  New South Wales
6  03-Jun-2018  Unprovoked     BRAZIL       Pernambuco
7  27-May-2018  Unprovoked        USA          Florida
8  26-May-2018  Unprovoked        USA          Florida
9  26-May-2018  Unprovoked        USA          Florida

                                            Location      Activity Gender  \
0                        Oceanside, San Diego County      Paddling      F
1                     St. Simon Island, Glynn County      Standing      F
2                                       Habush, Oahu       Surfing      M
3                                 Arrawarra Headland       Surfing      M
4                                           La Ticla   Free diving      M
5                                 Flat Rock, Ballina  Kite surfing      M
6                              Piedade Beach, Recife      Swimming      M
7  Lighhouse Point Park, Ponce Inlet, Volusia County       Fishing      M
8                       Cocoa Beach, Brevard  County       Walking      M
9                      Daytona Beach, Volusia County      Standing      M

       Age Fatal       Time          Species
0       57     N    Evening      White shark
1       11     N  Afternoon          Unknown
2       48     N    Morning          Unknown
3  Unknown     N    Unknown        2 m shark
4  Unknown     N    Unknown  Tiger shark, 3m
5  Unknown     N    Unknown          Unknown
6       18     Y  Afternoon      Tiger shark
7       52     N    Unknown  Lemon shark, 3'
8       15     N    Evening   Bull shark, 6'
9       12     N  Afternoon          Unknown

In [234]:
data_frame.describe(include="all").T

         count unique                               top  freq
Date      6302   5433                              1957    11
Type      6298      8                        Unprovoked  4595
Country   6252    212                               USA  2229
Area      5847    825                           Florida  1037
Location  5762   4108  New Smyrna Beach, Volusia County   163
Activity  5758   1532                           Surfing   971
Gender    5735      2                                 M  5098
Age       3471    157                                17   154
Fatal     5691      2                                 N  4302
Time      2935      4                         Afternoon  1387
Species   3464   1549                       White shark   163